JRELEASER_MAVENCENTRAL_USERNAME = "dilip.dhankecha"
JRELEASER_MAVENCENTRAL_PASSWORD = "Shayona@291120"
JRELEASER_NEXUS2_USERNAME = "dilip.dhankecha"
JRELEASER_NEXUS2_PASSWORD = "Shayona@291120"
JRELEASER_GPG_PASSPHRASE = "Shayona@291120"
JRELEASER_MAVENCENTRAL_SONATYPE_USERNAME = "dilip.dhankecha"