server:
  port: 8080

spring:
  jpa:
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/dao-poc
    username: root
    password:
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    schemas: public

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /ui/swagger-ui
    show-common-extensions: true
    csrf:
      enabled: true
  api-docs:
    path: /docs/api-docs